# Generated by Django 5.1.5 on 2025-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0003_remove_cartitem_cart_remove_orders_cart_id_and_more"),
        ("Customer", "0001_initial"),
        ("Shop", "0004_delete_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerDetails",
        ),
    ]
