# Generated by Django 5.1.5 on 2025-04-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0002_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="greeneryproducts",
            name="content",
        ),
        migrations.AlterField(
            model_name="greeneryproducts",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Shop.categories"
            ),
        ),
        migrations.AlterField(
            model_name="greeneryproducts",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="greeneryproducts",
            name="image",
            field=models.ImageField(upload_to="Greenery_products"),
        ),
    ]
