# Generated by Django 5.1.5 on 2025-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0003_remove_greeneryproducts_content_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
