# Generated by Django 5.1.5 on 2025-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0002_orders_payment_productorders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="cart_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="user",
        ),
        migrations.RemoveField(
            model_name="productorders",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="productorders",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Orders",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="ProductOrders",
        ),
    ]
